### ISSUE TITLE
validator is not starting

### ISSUE THREAD

**Issue by dariusz-bzowka-chain-insight** [Open0xScope/openscope#7]
my config.ini

[miner]
## If you are a miner
keyfile = my_key
url = http://127.0.0.1:5000/ [IP address and port where your miner service is running]

[validator]
## If you are a validator
name = myValid
keyfile = my_key
interval = 800 #This is recommend to align with the subnet tempo (800 s)
isTestnet = 1 #Whether using commune testnet: 1 means testnet; others means mainnet

[api]
url = http://47.236.87.93:8000/
For testnet: url = http://47.236.87.93:8000/  
mainnet: url = http://8.219.104.233:8000/

my validator key registration:
comx -t module register myValid my_key 14

your response: 
Using node: wss://testnet-commune-api-node-0.communeai.net
10.0 $COMAI will be permanently burned. Do you want to continue? [y/N]: y

I run validator:
python3 src/openscope/validator/validator.py

your response:
2024-08-19 12:31:23.286 | INFO     | __main__:timer_func:377 - timer_func begin
check validator time: 2024-08-19 12:31:23
2024-08-19 12:31:23.287 | INFO     | __main__:task_get_protect_address:299 - task_get_protect_address begin
2024-08-19 12:31:23.788 | INFO     | __main__:task_get_protect_address:301 - PROTECT_ADDRESS: 0
2024-08-19 12:31:23.789 | INFO     | __main__:task_get_protect_address:305 - task_get_protect_address end
2024-08-19 12:31:23.789 | INFO     | __main__:task_not_active_elimination:362 - task_not_active_elimination begin
2024-08-19 12:31:24.289 | INFO     | __main__:task_not_active_elimination:367 - not_active_elimination get nothing
2024-08-19 12:31:24.289 | INFO     | __main__:task_not_active_elimination:372 - task_not_active_elimination end
2024-08-19 12:31:24.289 | INFO     | __main__:task_copy_trading_elimination:348 - task_copy_trading_elimination begin
2024-08-19 12:31:24.782 | INFO     | __main__:task_copy_trading_elimination:353 - copy_trading_elimination get nothing
2024-08-19 12:31:24.783 | INFO     | __main__:task_copy_trading_elimination:358 - task_copy_trading_elimination end
2024-08-19 12:31:24.783 | INFO     | __main__:task_mdd_elimination:309 - task_mdd_elimination begin
2024-08-19 12:31:24.783 | INFO     | __main__:task_mdd_elimination:315 - mdd_elimination get nothing
2024-08-19 12:31:24.783 | INFO     | __main__:task_mdd_elimination:320 - task_mdd_elimination end
2024-08-19 12:31:24.783 | INFO     | __main__:task_roi_elimination:324 - task_roi_elimination begin
2024-08-19 12:31:24.784 | INFO     | __main__:task_roi_elimination:339 - roi_elimination get nothing
2024-08-19 12:31:24.784 | INFO     | __main__:task_roi_elimination:344 - task_roi_elimination end
2024-08-19 12:31:24.784 | INFO     | __main__:timer_func:398 - timer_func end:
NOT_ACTIVE_ELIMINATION_TARGET_TIME: 1724149883
COPY_TRADING_ELIMINATION_TARGET_TIME: 1724149883
PROTECT_ADDRESS_TARGET_TIME: 1724063783
MDD_ELIMINATION_TARGET_TIME: 1724067083
ROI_ELIMINATION_TARGET_TIME: 1724149883
Traceback (most recent call last):
  File "/root/openscope/src/openscope/validator/validator.py", line 456, in <module>
    validator.validation_loop(config)
  File "/root/openscope/src/openscope/validator/validator.py", line 422, in validation_loop
    weighted_scores = asyncio.run(self.validate_step(config, self.netuid))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/openscope/src/openscope/validator/validator.py", line 175, in validate_step
    raise ValueError(
ValueError: validator key 5CK4zNZWta5jW5TUJ7pQZFd8gp6NneZii2Wv8jSCjYiCuZ58 is not registered in subnet

**Comment by zpc48** [comment]
please follow the validator document. This error means the address is not registered on mainnet. You registered on testnet, but run validator on mainnet

**Comment by dariusz-bzowka-chain-insight** [comment]
key is in test net, and config file (see above) is also test net.

**Comment by zpc48** [comment]
ok, but this error  indicates the address is unregistered. You can verify your registration by using the command: "comx --testnet module list --netuid 14"  to check whether you have registered successfully. By the way, the nodes of commune in testnet may occasionally experience network issues, so proceed with caution.
