### ISSUE TITLE
validator process fails

### ISSUE THREAD

**Issue by dariusz-bzowka-chain-insight** [Open0xScope/openscope#9]
1|val_omic | /usr/local/lib/python3.10/dist-packages/eth_utils/network.py:44: UserWarning: Network 345 with name 'Yooldo Verse Mainnet' does not have a valid ChainId. eth-typing should be updated with the latest networks.
1|val_omic |   warnings.warn(
1|val_omic | /usr/local/lib/python3.10/dist-packages/eth_utils/network.py:44: UserWarning: Network 12611 with name 'Astar zkEVM' does not have a valid ChainId. eth-typing should be updated with the latest networks.
1|val_omic |   warnings.warn(
1|val_omic | 2024-08-30 12:05:23.404 | INFO     | __main__:timer_func:377 - timer_func begin
1|val_omic | 2024-08-30 12:05:23.405 | INFO     | __main__:task_get_protect_address:299 - task_get_protect_address begin
1|val_omic | 2024-08-30 12:05:24.983 | INFO     | __main__:task_get_protect_address:301 - PROTECT_ADDRESS: 0
1|val_omic | 2024-08-30 12:05:24.984 | INFO     | __main__:task_get_protect_address:305 - task_get_protect_address end
1|val_omic | 2024-08-30 12:05:24.984 | INFO     | __main__:task_not_active_elimination:362 - task_not_active_elimination begin
1|val_omic | 2024-08-30 12:05:26.959 | INFO     | storage:_get_json_file:35 - File not found: data/accounts.json

1|val_omicron_openscope  | check validator time: 2024-08-30 12:05:23
1|val_omicron_openscope  | Traceback (most recent call last):
1|val_omicron_openscope  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 737, in _error_catcher
1|val_omicron_openscope  |     yield
1|val_omicron_openscope  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 1187, in read_chunked
1|val_omicron_openscope  |     chunk = self._handle_chunk(amt)
1|val_omicron_openscope  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 1129, in _handle_chunk
1|val_omicron_openscope  |     value = self._fp._safe_read(amt)  # type: ignore[union-attr]
1|val_omicron_openscope  |   File "/usr/lib/python3.10/http/client.py", line 633, in _safe_read
1|val_omicron_openscope  |     raise IncompleteRead(data, amt-len(data))
1|val_omicron_openscope  | http.client.IncompleteRead: IncompleteRead(9572 bytes read, 668 more expected)
1|val_omicron_openscope  | The above exception was the direct cause of the following exception:
1|val_omicron_openscope  | Traceback (most recent call last):
1|val_omicron_openscope  |   File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 816, in generate
1|val_omicron_openscope  |     yield from self.raw.stream(chunk_size, decode_content=True)
1|val_omicron_openscope  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 1040, in stream
1|val_omicron_openscope  |     yield from self.read_chunked(amt, decode_content=decode_content)
1|val_omicron_openscope  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 1172, in read_chunked
1|val_omicron_openscope  |     with self._error_catcher():
1|val_omicron_openscope  |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
1|val_omicron_openscope  |     self.gen.throw(typ, value, traceback)
1|val_omicron_openscope  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 764, in _error_catcher
1|val_omicron_openscope  |     raise ProtocolError(f"Connection broken: {e!r}", e) from e
1|val_omicron_openscope  | urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(9572 bytes read, 668 more expected)', IncompleteRead(9572 bytes read, 668 more expected))
1|val_omicron_openscope  | During handling of the above exception, another exception occurred:
1|val_omicron_openscope  | Traceback (most recent call last):
1|val_omicron_openscope  |   File "/root/openscope/src/openscope/validator/validator.py", line 456, in <module>
1|val_omicron_openscope  |     validator.validation_loop(config)
1|val_omicron_openscope  |   File "/root/openscope/src/openscope/validator/validator.py", line 422, in validation_loop
1|val_omicron_openscope  |     weighted_scores = asyncio.run(self.validate_step(config, self.netuid))
1|val_omicron_openscope  |   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
1|val_omicron_openscope  |     return loop.run_until_complete(main)
1|val_omicron_openscope  |   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
1|val_omicron_openscope  |     return future.result()
1|val_omicron_openscope  |   File "/root/openscope/src/openscope/validator/validator.py", line 198, in validate_step
1|val_omicron_openscope  |     orders = get_recent_orders(val_ss58, pub_key, timestamp, signature, tradetime)
1|val_omicron_openscope  |   File "/root/openscope/src/openscope/validator/trade.py", line 404, in get_recent_orders
1|val_omicron_openscope  |     resp = requests.get(url, params=params, timeout=25)
1|val_omicron_openscope  |   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get
1|val_omicron_openscope  |     return request("get", url, params=params, **kwargs)
1|val_omicron_openscope  |   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
1|val_omicron_openscope  |     return session.request(method=method, url=url, **kwargs)
1|val_omicron_openscope  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
1|val_omicron_openscope  |     resp = self.send(prep, **send_kwargs)
1|val_omicron_openscope  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 747, in send
1|val_omicron_openscope  |     r.content
1|val_omicron_openscope  |   File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 899, in content
1|val_omicron_openscope  |     self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
1|val_omicron_openscope  |   File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 818, in generate
1|val_omicron_openscope  |     raise ChunkedEncodingError(e)
1|val_omicron_openscope  | requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(9572 bytes read, 668 more expected)', IncompleteRead(9572 bytes read, 668 more expected))
PM2                      | App [val_omicron_openscope:1] exited with code [1] via signal [SIGINT]

**Comment by zpc48** [comment]
We updated our code recently to fix this problem.

**Comment by Khan-arsh** [comment]
Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by dariusz-bzowka-chain-insight** [comment]
if the following output
```
python3 src/openscope/validator/validator.py
2024-09-23 14:36:19.746 | INFO     | __main__:timer_func:381 - timer_func begin
check validator time: 2024-09-23 14:36:19
2024-09-23 14:36:19.747 | INFO     | __main__:task_get_protect_address:299 - task_get_protect_address begin
2024-09-23 14:36:20.265 | INFO     | __main__:task_get_protect_address:301 - PROTECT_ADDRESS: 0
2024-09-23 14:36:20.265 | INFO     | __main__:task_get_protect_address:305 - task_get_protect_address end
2024-09-23 14:36:20.265 | INFO     | __main__:task_not_active_elimination:366 - task_not_active_elimination begin
2024-09-23 14:36:23.269 | INFO     | storage:_get_json_file:35 - File not found: data/accounts.json
2024-09-23 14:36:23.343 | INFO     | __main__:validate_step:198 - fetch recent orders start, timestamp: 0
fetch data page: 1
fetch data page: 2
fetch data page: 1
fetch data page: 2
fetch data page: 3
fetch data page: 4
fetch data page: 3
fetch data page: 5
fetch data page: 6
fetch data page: 7
fetch data page: 4
fetch data page: 8
fetch data page: 5
fetch data page: 9
fetch data page: 6
fetch data page: 10
fetch data page: 7```
is expected from the validator, we can close the task and celebrate success.
